server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registrationdb
    username: root
    password: 38403077@f
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: senelwafarthy@gmail.com
    password: 38403077@senelwa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



